# Generated by Django 5.0.2 on 2024-02-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('skill', models.CharField(max_length=255)),
                ('model_answer', models.CharField(max_length=2000)),
            ],
        ),
    ]
